import { ProjectPost, ProjectField, ProjectStage } from '../types';

const STORAGE_KEY_POSTS = 'launchpad_posts';
const STORAGE_KEY_USER = 'launchpad_user';

const SEED_DATA: ProjectPost[] = [
  {
    id: '1',
    founderName: 'Alex Chen',
    projectName: 'NeuroFlow',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    description: 'Building the next generation of focus tools using ambient soundscapes generated by AI. We are looking for a frontend wizard who loves clean UI.',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    field: ProjectField.AI,
    stage: ProjectStage.MVP,
    compensation: '5% Equity + Stipend',
    roles: ['Frontend', 'UI/UX']
  },
  {
    id: '2',
    founderName: 'Sarah Jenkins',
    projectName: 'EduMatch',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString(),
    description: 'Tinder for study groups. Connect with students in your university taking the same courses. Need a backend dev familiar with Supabase.',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    field: ProjectField.EDTECH,
    stage: ProjectStage.IDEA,
    compensation: 'Co-founder Equity',
    roles: ['Backend', 'Marketing']
  }
];

export const getPosts = (): ProjectPost[] => {
  const stored = localStorage.getItem(STORAGE_KEY_POSTS);
  if (!stored) {
    localStorage.setItem(STORAGE_KEY_POSTS, JSON.stringify(SEED_DATA));
    return SEED_DATA;
  }
  return JSON.parse(stored);
};

export const createPost = (post: Omit<ProjectPost, 'id' | 'postedDate'>): ProjectPost => {
  const posts = getPosts();
  const newPost: ProjectPost = {
    ...post,
    id: crypto.randomUUID(),
    postedDate: new Date().toISOString()
  };
  const updatedPosts = [newPost, ...posts];
  localStorage.setItem(STORAGE_KEY_POSTS, JSON.stringify(updatedPosts));
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('posts:changed'));
  }
  return newPost;
};

export const updatePost = (updated: ProjectPost): ProjectPost => {
  const posts = getPosts();
  const idx = posts.findIndex(p => p.id === updated.id);
  if (idx >= 0) {
    posts[idx] = { ...posts[idx], ...updated };
    localStorage.setItem(STORAGE_KEY_POSTS, JSON.stringify(posts));
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('posts:changed'));
    }
    return posts[idx];
  }
  return createPost({
    founderName: updated.founderName,
    projectName: updated.projectName,
    field: updated.field,
    stage: updated.stage,
    compensation: updated.compensation,
    deadline: updated.deadline,
    description: updated.description,
    imageUrl: updated.imageUrl,
    roles: updated.roles,
  });
};

export const deletePost = (id: string): void => {
  const posts = getPosts();
  const next = posts.filter(p => p.id !== id);
  localStorage.setItem(STORAGE_KEY_POSTS, JSON.stringify(next));
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('posts:changed'));
  }
};

export const getPostsByFounder = (name: string): ProjectPost[] => {
  return getPosts().filter(p => p.founderName === name);
};

export const getUser = (): string => {
  let user = localStorage.getItem(STORAGE_KEY_USER);
  if (!user) {
    user = 'Guest Founder';
    localStorage.setItem(STORAGE_KEY_USER, user);
  }
  return user;
};

export const saveUser = (name: string): void => {
  localStorage.setItem(STORAGE_KEY_USER, name);
};
